#!/bin/bash

cmd="$(basename "$0")"

FUNC="nvmet_pci_epf.0"
subsys="${FUNC}.nqn"
nrioq=4
#nrioq=$(nproc)
debug=0
mmio=0
model="Linux-nvme-pci"
mdts="128"
mqes="128"

nsdev=""
sched=""

tcpaddr=""
tcpport=""

ctrlopts=""

function exit_failed()
{
	echo "$1"
	exit 1
}

function usage()
{
	echo "Usage:"
	echo "    ${cmd} [-h | --help]"
	echo "    ${cmd} [options] start"
	echo "    ${cmd} stop"
	echo "Start command options:"
	echo "  --debug-epf        : Turn on nvme epf debug messages"
	echo "  --debug-nvme       : Turn on nvme fabrics debug messages"
	echo "  --debug-pci        : Turn on pci controller debug messages"
	echo "  --debug            : Turn on epf, nvme and pci kernel debug messages"
	echo "  --disable-dma      : Disable use of DMA (use mmio transfers)"
	echo "  --model <str>      : Use <str> as device model name"
	echo "                              (default: Linux-pci-epf)"
	echo "  --mdts <size (KB)> : Set maximum command transfer size"
	echo "                       (default 128 KB)"
	echo "  --mqes <num>       : Set maximum queue size"
	echo "  --buffered-io      : Used buffered IOs on the target"
	echo "                       (default: no)."
	echo "  --nrioq <num>      : Set maximum number of I/O queues"
	echo "                       (default: number of CPUs)."
	echo "  --nsdev <path>     : Use file or block device for the namespace"
	echo "                       (default: use null_blk and /dev/nullb0)."
	echo "  --sched <sched>    : Use the <sched> I/O scheduler for the NS device"
}

# Check options
while [ "${1#-}" != "$1" ]; do
	case "$1" in
	-h | --help)
		usage
		exit 0
		;;
	--debug-epf)
		debug_epf=1
		;;
	--debug-nvme)
		debug_nvme=1
		;;
	--debug-pci)
		debug_pci=1
		;;
	--debug)
		debug_epf=1
		debug_nvme=1
		debug_pci=1
		;;
	--disable-dma)
		mmio=1
		;;
	--model)
		shift
		model="$1"
		;;
	--mdts)
		shift
		mdts="$1"
		;;
	--mqes)
		shift
		mqes="$1"
		;;
	--buffered-io)
		bufferedio=1
		;;
	--nrioq)
		shift
		nrioq=$1
		;;
	--nsdev)
		shift
		nsdev="$1"
		;;
	--sched)
		shift
		sched="$1"
		;;
	-*)
		echo "Unknow option $1"
		exit 1
		;;
	esac
	shift
done

if [ "$1" == "" ]; then
	usage
	exit 1
fi

if [ ${nrioq} -le 0 ]; then
	echo "Invalid maximum number of I/O queues."
	exit 1
fi

if [ "${nsdev}" == "" ]; then
	modprobe null_blk \
		nr_devices=1 \
		submit_queues="$(nproc --all)" \
		gb=1024 max_sectors=2048 || \
		exit_failed "Load null_blk failed"
	nsdev="/dev/nullb0"
fi

if [ "${sched}" != "" ]; then
	modprobe ${sched} || \
                exit_failed "Load ${sched} failed"
        echo "${sched}" > /sys/block/$(basename ${nsdev})/queue/scheduler || \
                exit_failed "Set ${sched} failed"
fi

action="$1"

function nvme_setup_subsys()
{
	local port="1"
	local ns="1"

	echo "Creating NVMe subsystem ${subsys}, target ${nsdev}"

	echo "    Loading nvmet-pci"
	modprobe nvmet-pci || \
		exit_failed "Load nvmet-pci failed"

	# Create the subsystem
	echo "    Creating subsystem ${subsys}"
	cd /sys/kernel/config/nvmet/subsystems
	mkdir "${subsys}"

	echo -n "${model}" > ${subsys}/attr_model
	echo 1 > ${subsys}/attr_allow_any_host
	echo ${nrioq} > ${subsys}/attr_qid_max

	# Create a namespace
	echo "    Creating namespace 1"
	nsdir="${subsys}/namespaces/${ns}"
	mkdir "${nsdir}"
	echo -n "${nsdev}" > "${nsdir}/device_path"

	if [ "${bufferedio}" == "1" ]; then
		echo "    Enabling buffered IO"
		echo "1" > "${nsdir}/buffered_io" || \
			exit_failed "Enabling buffered IO failed"
	else
		echo "0" > "${nsdir}/buffered_io"
	fi

	echo 1 > "${nsdir}/enable"

	# Create an NVMe port
	echo "    Creating port 1"
	cd /sys/kernel/config/nvmet/ports
	mkdir "${port}"
	echo "${mqes}" > ${port}/param_max_queue_size || \
		exit_failed "Set MQES failed"

	echo -n "pci" > ${port}/addr_trtype || \
		exit_failed "Set PCI transport failed"

	ln -s /sys/kernel/config/nvmet/subsystems/${subsys} \
		/sys/kernel/config/nvmet/ports/${port}/subsystems/${subsys}
}

function nvme_teardown_subsys()
{
	local port="1"
	local ns="1"
	local portdir="/sys/kernel/config/nvmet/ports/${port}"
	local subsysdir="/sys/kernel/config/nvmet/subsystems/${subsys}"
	local nsdir="${subsysdir}/namespaces/${ns}"

	echo "Deleting NVMe PCI subsystem ${subsys}, target ${nsdev}"

	if [ -d "${nsdir}" ]; then
		echo 0 > "${nsdir}/enable"
	fi

	if [ -d "${portdir}/subsystems/${subsys}" ]; then
		rm /sys/kernel/config/nvmet/ports/${port}/subsystems/${subsys} || \
			exit_failed "Detach subsystem ${subsys} from port ${port} failed"
	fi

	if [ -d "${portdir}" ]; then
		rmdir /sys/kernel/config/nvmet/ports/${port} || \
			exit_failed "Delete port ${port} failed"
	fi

	if [ -d "${nsdir}" ]; then
		rmdir "${nsdir}" || \
			exit_failed "Delete subsystem ${subsys} namespace ${ns} failed"
	fi

	if [ -d "${subsysdir}" ]; then
		rmdir "/sys/kernel/config/nvmet/subsystems/${subsys}" || \
			exit_failed "Delete subsystem ${subsys} failed"
	fi

	echo "    Removing nvmet-pci"
	rmmod nvmet-pci || \
		exit_failed "Remove nvmet-pci failed"
	echo "    Removing nvmet"
	rmmod nvmet || \
		exit_failed "Remove nvmet failed"
}

function nvme_pci_start()
{
	# Enable pr_debug
	if [ "${debug_epf}" == "1" ]; then
		echo "Enabling epf debug"
		echo 8 > "/proc/sys/kernel/printk"
		echo -n 'module nvmet-pci +p;' > \
			"/sys/kernel/debug/dynamic_debug/control"
	fi

	if [ "${debug_nvme}" == "1" ]; then
		echo "Enabling nvme debug"
		echo 8 > "/proc/sys/kernel/printk"
		echo -n 'module nvmet +p;' > \
			"/sys/kernel/debug/dynamic_debug/control"
	fi

	if [ "${debug_pci}" == "1" ]; then
		echo "Enabling pci debug"
		echo 8 > "/proc/sys/kernel/printk"
		echo -n 'file drivers/pci/controller/dwc/pcie-dw-rockchip.c +p;' > \
			"/sys/kernel/debug/dynamic_debug/control"
		echo -n 'file drivers/pci/controller/dwc/pcie-designware.c +p;' > \
			"/sys/kernel/debug/dynamic_debug/control"
		echo -n 'file drivers/pci/controller/dwc/pcie-designware-ep.c +p;' > \
			"/sys/kernel/debug/dynamic_debug/control"
	fi

	# Setup the subsystem.
	nvme_setup_subsys || \
		exit_failed "Setup NVMe PCI controller failed"

	# Check controller
	cd /sys/kernel/config/pci_ep || \
		exit_failed "Missing PCI-EP"

	controller="$(find controllers -name "*pcie*")"
	if [ -z "${controller}" ]; then
		exit_failed "PCI EP Controller not found"
	fi

	# Setup the NVMe endpoint function
	echo "Creating NVMe endpoint function ${FUNC}..."
	mkdir "functions/nvmet_pci_epf/${FUNC}" || \
		exit_failed "Create ${FUNK} failed"
	sleep 0.5

	echo "    Set Vendor ID to Sandisk Corp (0x15b7)"
	echo 0x15b7 > "functions/nvmet_pci_epf/${FUNC}/vendorid" || \
		exit_failed "Set vendorid failed"

	echo "    Set Device ID to dummy 0x5fff"
	echo 0x5fff > "functions/nvmet_pci_epf/${FUNC}/deviceid" || \
		exit_failed "Set deviceid failed"

	echo "    Set MSIX interrupts"
	echo 32 > "functions/nvmet_pci_epf/${FUNC}/msix_interrupts" || \
		exit_failed "Set msix_interrupts failed"

	echo "    Set MSI interrupts"
	echo 32 > "functions/nvmet_pci_epf/${FUNC}/msi_interrupts" || \
		exit_failed "Set msi_interrupts failed"

	if [ "${mmio}" == "1" ]; then
		echo "    Disabling DMA"
		echo "0" > "functions/nvmet_pci_epf/${FUNC}/nvme/dma_enable" || \
			exit_failed "Disable DMA failed"
	fi

	echo "${mdts}" > "functions/nvmet_pci_epf/${FUNC}/nvme/mdts_kb" || \
		exit_failed "Set MDTS failed"

	echo "${subsys}" > "functions/nvmet_pci_epf/${FUNC}/nvme/subsysnqn" || \
		exit_failed "Set subsys NQN failed"

	# Start the NVMe endpoint function
	echo "Attaching NVMe endpoint function to PCI EP controller ${controller}..."
	ln -s "functions/nvmet_pci_epf/${FUNC}" "${controller}/" || \
		exit_failed "Attach function ${FUNC} to controller failed"

	echo "Starting the PCI controller..."
	echo 1 > "${controller}/start" || \
		exit_failed "Start the PCI EP controller failed"
}

function nvme_pci_stop()
{
	# Check controller
	cd /sys/kernel/config/pci_ep || \
		exit_failed "Missing PCI-EP"

	controller="$(find controllers -name "*pcie*")"
	if [ -z "${controller}" ]; then
		exit_failed "PCI EP Controller not found"
	fi

	echo "Stopping the PCI controller"
	echo 0 > "${controller}/start" || \
		exit_failed "Stop the PCI EP controller failed"

	echo "Detaching NVMe PCI endpoint function from PCI EP controller ${controller}..."
	rm "${controller}/${FUNC}" || \
		exit_failed "Detach function ${FUNC} from controller failed"

	echo "Destroying NVMe PCI endpoint function ${FUNC}..."
	rmdir "functions/nvmet_pci_epf/${FUNC}" || \
		exit_failed "Remove ${FUNC} failed"

	nvme_teardown_subsys

	rmmod nvmet-pci
}

case "${action}" in
start)
	nvme_pci_start
	;;
stop)
	nvme_pci_stop
	;;
*)
	echo "Unknow action ${action}"
	exit 1
	;;
esac

