#!/bin/sh

# Mount sysfs and procfs
/bin/mount -t sysfs sysfs /sys
/bin/mount -t proc proc /proc

# When booting using an embedded initramfs, devtmpfs is not
# automatically mounted. Detect this here and mount it if needed.
devtmpfs=$(mount | grep -c devtmpfs)
if [ $devtmpfs == 0 ]; then
    /bin/mount -t devtmpfs devtmpfs /dev
fi

# use the /dev/console device node from devtmpfs if possible to not
# confuse glibc's ttyname_r().
# This may fail (E.G. booted with console=), and errors from exec will
# terminate the shell, so use a subshell for the test
if (exec 0</dev/console) 2>/dev/null; then
    exec 0</dev/console
    exec 1>/dev/console
    exec 2>/dev/console
fi

echo "        __  _"
echo "       / / (_) ____   _   _ __  __"
echo "      / /  | ||  _ \\ | | | |\\ \\/ /"
echo "     / /___| || | | || |_| | >  < "
echo "    /_____/|_||_| |_| \\____|/_/\\_\\"
echo "      RISC-V Kendryte K210 NOMMU"

exec /bin/sh
