#!/bin/sh

# This script replaces the default busybox init process to avoid having that
# process staying alive and sleeping in the background, (uselessly) consuming
# precious memory.

# Mount devtmpfs, procfs and sysfs
/bin/mount -t proc proc /proc
/bin/mount -t devtmpfs devtmpfs /dev
/bin/mount -t sysfs sysfs /sys

# Use the /dev/console device node from devtmpfs if possible to not
# confuse glibc's ttyname_r().
# This may fail (E.G. booted with console=), and errors from exec will
# terminate the shell, so use a subshell for the test
if (exec 0</dev/console) 2>/dev/null; then
    exec 0</dev/console
    exec 1>/dev/console
    exec 2>/dev/console
fi

# Create links to fd, stderr, stdin and stdout
ln -s /proc/self/fd /dev/fd
ln -s /proc/self/fd/2 /dev/stderr
ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout

# Print a fun logo :)
echo "          __  _"
echo "         / / (_) ____   _   _ __  __"
echo "        / /  | ||  _ \\ | | | |\\ \\/ /"
echo "       / /___| || | | || |_| | >  < "
echo "      /_____/|_||_| |_| \\____|/_/\\_\\"
echo "    64-bits RISC-V Kendryte K210 NOMMU"
echo ""

# Finally, let's start an interactive shell
exec /bin/sh
