#!/bin/sh

function ip_addr()
{
	/sbin/ifconfig eth0 | grep -i mask | awk '{print $2}' | cut -f2 -d':'
}

function kmsg()
{
	echo "$1"
}

function banner()
{
kmsg ""
kmsg "       ____             __   ________          ______"
kmsg "      / __ \\____  _____/ /__/ ____/ /_        / ____/___"
kmsg "     / /_/ / __ \\/ ___/ //_/___ \\/ __ \\______/ __/ / __ \\"
kmsg "    / _, _/ /_/ / /__/ ,< ____/ / /_/ /_____/ /___/ /_/ /"
kmsg "   /_/ |_|\\____/\\___/_/|_/_____/_.___/     /_____/ .___/"
kmsg "                                                /_/"
kmsg ""

kmsg "   $(dmesg -t | grep "Machine model")"
kmsg "   CPU cores: $(nproc --all)"
kmsg "   $(dmesg -t | grep "Memory:" | cut -f1 -d'(')"
kmsg "   Kernel: $(uname -r) $(uname -m)"
kmsg "   IP Address: $(ip_addr)"
kmsg ""
}

case "$1" in
  start)
	sleep 3
	banner
        ;;
  stop)
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
